### ISSUE TITLE
Diff with master... (i.e. 3 dots for common ancestry) shows highlighted positional changes, but shows current file on both sides

### ISSUE THREAD

**Issue by benjaminramsden** [CJTozer/SublimeDiffView#31]
Repro:
Alt+Shift+D
Choose: master... (note 3 dots)

Output shows on the LHS and RHS the same file, which is the current state in HEAD, but additions are highlighted correctly (if the file on the LHS was correct).

**Comment by CJTozer** [comment]
Looks to work for `master...branch_a` (when not on branch_a) and `master...` (when on branch_a) when I try it.

Any errors on the console?

**Comment by benjaminramsden** [comment]
No output to the sublime console.

Worth noting this is in use with git-svn, and the last time the code was merged for the two branches is some 60 commits ago, I don't know if you have some upper limit to how far this could work backwards.

**Comment by CJTozer** [comment]
Can you check your version?

`Ctrl+Shift+P`, `Package Control: List Packages`, then check the text for `DiffView`.

If it's lower than `v1.0.1`, please update with `Ctrl+Shift+P`, `Package Control: Upgrade Package` and select `DiffView`.

**Comment by benjaminramsden** [comment]
I'm currently using v1.0.1, so that does not appear to be the issue.

**Comment by CJTozer** [comment]
Aha - well I can repro in another repository.  Bugs in `get_file_versions` not giving the right file versions for a merge-base diff.

**Comment by CJTozer** [comment]
Release `v1.0.2` should fix this.
