### ISSUE TITLE
Completely freezes ST3

### ISSUE THREAD

**Issue by Gabriel-p** [CJTozer/SublimeDiffView#46]
Just installed this package in ST3 build 3126 (running on [elementary OS](https://elementary.io/) Loki, 64 bit).

Went to a file with changes in my git repo, hit `Alt+Shift+D` and ST3 freezed instantly. Forced close, and tried again: again freezed.

Not sure how to debug this since I can't even see the console.

**Comment by CJTozer** [comment]
Hmm, not sure what to make of this, but thanks for reporting.  A few questions/suggestions:
* Can you run `Alt+Shift+D` (or use the command palette to do a diff) with the console open before you try the diff?
* If so, please try running the diff with `debug: true` set in the DiffView user settings (`Preferences -> Package Settings -> DiffView -> Settings - User`), and get that output if possible?
* I assume `git diff` works OK on the command line?
* Can you get the list of processes running beneath ST3 (would be `ps auxf` under 'normal' Linux)

**Comment by Gabriel-p** [comment]
I think I got it. I had my `.gitconfig` set to:

```
[diff]
        external = meld
	tool = meld
```

Apparently the `external = meld` line was causing problems with `git diff`. I removed it and now the package works as expected.

Thank you!
