### ISSUE TITLE
Condensed Diff View (1 line per file)

### ISSUE THREAD

**Issue by tnrich** [CJTozer/SublimeDiffView#50]
Hey there,

First off, thank you for the awesome diff tool! It makes my life a lot easier!

So, my only pet peeve with the tool is that sometimes I end up arrow-down-ing through a bunch of lines that I don't really care about. It would be awesome to have a way to collapse the list of file changes into just a single list of the changed files. 

So if instead of this:
![image](https://user-images.githubusercontent.com/2730609/27820115-16717eea-6052-11e7-845e-ba67b5405540.png)
There was an option to change it to just have 1 line per file which would bring you to the first change of the given file. As it stands now I have to arrow-down through a bunch of package json changes that are really all right next to each other to get to the next file I'm interested in. 

Does that make sense?

Thanks again!

**Comment by CJTozer** [comment]
Interesting idea, and I don't think it should be all that hard.

You'll lose the ability to use up/down to step through the changes while keeping the left/right views in sync, which might make this a bit less usable when you get to the file you _do_ care about.

One alternative I can think of is to use left/right (or some other key binding) to skip file-by-file so you can have the best of both worlds, but I worry that this might not be the most discoverable option.

Anyway, thanks for the feedback, I'd be interested to hear your thoughts.

**Comment by tnrich** [comment]
Hey Chris, so I think my ideal interface would be something where you would have the collapsed, 1-line per file view as the default, and then have an easy way to expand the line to see all of the rest of the sub-file lines as well, but barring that, I think just having a user preference that you could set to decide which view you want by default would be enough. 

I personally don't use the line by line functionality that often so wouldn't be too sad to see it go.

Just my 2 cents

**Comment by CJTozer** [comment]
Added this option in [v1.2.0](https://github.com/CJTozer/SublimeDiffView/releases/tag/v1.2.0) - please let me know what you think.

Note this might take a little while to get updated through Package Control - you can check whether you've got the latest version by running `Package Control: List Packages` and seeing whether you have DIffView version v1.1.3 or v1.2.0.

**Comment by tnrich** [comment]
Awesome!! Thank you very much! I can't wait to try it out!

**Comment by tnrich** [comment]
I've just tried it out and it is awesome. Thanks @CJTozer! One thing I'd like to have is the ability to jump to the next diff via a command, like "DiffView: Jump to next diff". The reason being is that once you're inside a file with the condensed view, it is harder to navigate than I had expected because the scroll bar doesn't affect both files. 

Other than that it is just what I was looking for. 

Thanks!

**Comment by CJTozer** [comment]
Yeah the scrollbar is only triggered by selecting the next diff, I realise that's a limitation.

The main idea is that you hit `Tab` to open the file you care about, and step through as normal, but I take your point on having a "next diff" command - probably not too hard to fix, so I've raised #52 to cover the idea.
