### ISSUE TITLE
skip non-text filetypes

### ISSUE THREAD

**Issue by Maik93** [CJTozer/SublimeDiffView#53]
Hi,
I think it would be useful to skip differences for non textual files, e.g. *.pdf, *.png etc... There's a way we can do it?

**Comment by CJTozer** [comment]
Can I check - do you at least see "Unable to decode file..." for the *.pdf etc. files?

I don't see any harm in having an exclude pattern for DiffView - that could be configurable in the settings.  Not sure I want it turned on globally though in case people are using the file list to remind them about changes in binary-format files...

**Comment by Maik93** [comment]
Yes, I can see "Unable to decode file...", the actual thing that's annoying is that it's replicated too much time:
![image](https://user-images.githubusercontent.com/7384336/29359626-b048b1a6-827f-11e7-8d6a-a10bd305ee0b.png)
I've changed only few rows on my .tex file and I've 62 entries on DiffView... It would be nice if there's be only one entry, or as you said, a settings configuration for pattern exclusions.
Thanks for help, you've already done a great job so far! ;)

**Comment by CJTozer** [comment]
Ah interesting - so the difference between this and the cases I've tested previously is that your VCS is able to produce a list of deltas - but Sublime is unable to show the file.  Previously I've only seen one line as Git (etc.) just state that the binary file has changed, and there is no breakdown of the changes.  Which VCS are you using?

One thing you can try to make this nicer is the recently added configuration option `"collapse_diff_list": true` that starts the top pane with each file's changes folded down to one line - and uses `tab` to expand/collapse.

Reclassifying as a bug though, as there's no point at all having multiple lines for an unreadable file.

**Comment by Maik93** [comment]
It's only Git, under Windows, latest release from [here](https://git-scm.com/downloads).

`Settings - Default` is read only, but anything in `Settings - User` seems to doesn't have any effect:
![image](https://user-images.githubusercontent.com/7384336/29360633-20d3209c-8284-11e7-808c-10c49f0066d8.png)
but DiffView is still as in the first screen.

**Comment by CJTozer** [comment]
Hmm, git definitely too clever for its own good then!

However, I don't get why your setting's not working - I get the following when I turn it on (first file is expanded with `Tab`, second is collapsed).

![image](https://user-images.githubusercontent.com/3398193/29361253-a151b680-827e-11e7-9d21-1b0cbe795a23.png)

Your settings look fine (though just to double-check, this is the DiffView package settings not the global settings that this needs to be set in).  Given it's not clear, could you maybe try one or more of the following:
* restart Sublime (shouldn't be necessary to pick up settings changes, but I've known it be weird in the past)
* grab any console output from running the diff (`Ctrl + '` in Windows to bring this up IIRC)
* I was also going to suggest that you try running DiffView in debug mode, but then realised that I didn't add any useful debugging to see what settings are in use - I should do that (and it will help here if the restart doesn't fix things).

**Comment by CJTozer** [comment]
Oh, also if you can check the DiffView version by running `Ctrl+Shift+P`, `Package Control: List Packages` then checking for DiffView - should be version `1.2.0`.

**Comment by Maik93** [comment]
Ok, I've got version `1.2.0`, and restarting Sublime makes `collapse_diff_list` work!

**Comment by CJTozer** [comment]
Fantastic - glad to hear it (and otherwise I'd be very confused).

So, this issue now just covers the case that when the file can't be opened to preview, the view should limit that file to a single change - even if the VCS is being smart and can show multiple diffs.

**Comment by Maik93** [comment]
Thanks for help, I've to close this post?
