### ISSUE TITLE
How to compare after pull from git

### ISSUE THREAD

**Issue by nguyenvanquan7826** [CJTozer/SublimeDiffView#58]
Hi, thank for this plugin but I have a question: After I pull project from github or gitlab, how to see different all change in a file? I try to it but can not! 
Thanks

**Comment by CJTozer** [comment]
Can you describe what you're trying to see here?  Perhaps one of these might be useful:

* After pulling a project, you want to see the difference between tag `0.5.1` and the current code, you do this by `Alt+Shift+D` (default key), then enter `0.5.1..` in the box and press enter.
* If you've made local changes and want to see them, you can leave the box blank to compare the latest commit and your local copy

Does that help?

**Comment by nguyenvanquan7826** [comment]
Hi, In my case:
I and my friend code in one project.
I have meger code form my friend on server and then I pull code from server to local. Now I want show all change of a file to know what different my code and my friend's code.

**Comment by CJTozer** [comment]
Ah, OK I understand.  There are two things you can try:

* turn on the [collapsible list](https://github.com/CJTozer/SublimeDiffView#collapsing-changes-list) option, so you just get one line in the view per file - then use `Tab` (by default) to expand the changes on the file you're interested in
* use `b1..b2 -- path/to/file` as the option to DiffView - this is the same as you'd use in the Git command line to see changes for only a subset of file locations

Hope that helps - let me know if it does, or if you have any further questions.
