### ISSUE TITLE
Very Cool, but the default key binding gets me every time :D

### ISSUE THREAD

**Issue by tilo** [CJTozer/SublimeDiffView#60]
Super useful package! thank you!

Alt-Shift-D is really hard to type, and very close to Cmd-Shift-D which does something very different :-P

Would also be good to see the Git Hash and current branch name on top of the side-by-side windows, so it's very clear what is shown...

**Comment by CJTozer** [comment]
Ha!  Yeah I didn't have a particularly great reason for picking that keybinding, but you can always change it in the settings if you want...

Thanks very much for the feedback though, and I like your idea (I have raised #61 to cover it).
