### ISSUE TITLE
Can this be used as a Git difftool?

### ISSUE THREAD

**Issue by gwerbin** [CJTozer/SublimeDiffView#63]
Git makes it possible to use an [external "difftool"](https://stackoverflow.com/a/949242/2954547) in place of the stock command-line pager-based diff viewer. Can DiffView be configured somehow as a Git difftool?

**Comment by CJTozer** [comment]
There is no way to use this Sublime plugin as a `difftool`.  You may want to check out [Sublime's own offering](https://www.sublimemerge.com/) of a stand-alone Git GUI.

(Disclaimer: I've not used this tool, but it certainly looks to have a lot of good features as a stand-alone application).

**Comment by gwerbin** [comment]
@CJTozer thanks for clarifying and thanks for the recommendation.

In theory, would it be possible to rig something up where `difftool` starts Sublime and then shows the diff using this plugin?

**Comment by CJTozer** [comment]
Well, interesting question.  Looking at the [Unofficial Docs](http://docs.sublimetext.info/en/latest/command_line/command_line.html) it seems there's a `--command` parameter you could pass to ST3 on start-up.

So in theory perhaps yes, you could get something _like_ this to work, but:
- it says that Window commands only work this way if ST3 is already running - and DiffView is a window command
- DiffView looks at project state, not an input diff, so it's likely that whatever the API is for `diftool` would need quite a lot of enhancements to make work in DiffView (to make it understand the parameters it was being passed)

So, yes in theory it's possible to rig something up, but I think it won't "just work" and would be quite fiddly to make it all line up - likely requiring quite a large enhancement on the plugin itself.

Thanks for your interest - sorry this doesn't meet the use case you're looking for.
