### ISSUE TITLE
Is it possible to use this package without version control system?

### ISSUE THREAD

**Issue by john-cj** [CJTozer/SublimeDiffView#68]
The issue title says it all. I'm not a professional developer and therefore I don't use Git or any another version control system in my work. However, I use DiffMerge desktop utility to see the difference between local files quite often. Is it possible to use this package in the same way? To diff two tabs without using Git, SVN, or Bazaar.

**Comment by CJTozer** [comment]
Thanks for the query!

But no, that's not what this plugin is designed for - such plugins already existed when I wrote this one.

I've not used either, but you might want to try one of:
* https://packagecontrol.io/packages/FileDiffs
* https://packagecontrol.io/packages/Compare%20Side-By-Side

...as on the face of it these seem to do what you want
